fix: UTXO being mixed up with multiple account in parallel
dashevo/wallet-lib pull request #233
Opened 2021-02-15 22:25 UTC by Alex-Werner

## Issue being fixed or feature implemented

This fix https://github.com/dashevo/wallet-lib/issues/229 and might fix an issue on which we cannot sign the UTXO that we received from getUTXOS() therefore blocking creating/broadcasting some transaction.
This is specific to working with multiple account might it be during same runtime or using persistance (when on first runtime we would use account 0, and second runtime account 1). 

## What was done?
- filter HD wallet subscription path on TransactionStreamWorker.
- filter on getUTXO on HD Wallet.

## How Has This Been Tested?
- Further tests should be added in another PR to cover multiple account working with a TXStream. 

## Breaking Changes
N/A

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added or updated relevant unit/integration/functional/e2e tests
- [X] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [X] I have assigned this pull request to a milestone

2021-02-17 11:01 UTC, antouhou reviewed
Can we add a unit to test this case?

2021-02-17 19:29 UTC, Alex-Werner commented
@antouhou Added unit test :)

2021-02-23 05:11 UTC, shumkov requested changes

2021-02-23 05:11 UTC, shumkov commented on src/types/Account/methods/getUTXOS.js
> +    if (addressType && ['external', 'internal', 'misc'].includes(addressType)) {
Super nested, hard to read.

Maybe try to decrease levels with:

```js
if (!addressType || !['external', 'internal', 'misc'].includes(addressType)) {
  continue;
}
```

http://blog.wilsonpage.co.uk/return-early/
https://blog.timoxley.com/post/47041269194/avoid-else-return-early

2021-02-23 08:54 UTC, Alex-Werner commented
Applied requested change

2021-02-23 11:17 UTC, shumkov approved these changes
Looks good!

2021-02-23 11:47 UTC, antouhou approved these changes
Looks good to me! Let's merge it after we publish 0.18, so we won't merge anything right at the release?

2021-02-25 09:33 UTC, merged